### PR TITLE
Two versions of the codec: one requiring reflection and one for tinygo

### PR DESCRIPTION
**Pull request by kyegupov**

### CODE REVIEW

**Comment by mnaamani** [comment]
There seems to be some minimal duplicate code across the two implementations. Is there a way to factor them out to a common package. I wonder though If its not really necessary to maintain two implementations in future and we will only rely on the 'noreflect' implementation, perhaps its not worth the effort.

**Comment by mnaamani** [comment]
Other than that, looks good and tests are passing.
Nice work!

**Comment by kyegupov** [comment]
There's definitely a way to reuse code. But it would require some effort and it was not a high-priority goal for me yet.

**Comment by kyegupov** [comment]
Can we merge in this PR?

**Pull request merged**
